@startuml
hide footbox
title see Profile
actor student  
boundary ":historyView"
control ":taskController"
entity   ":task"
activate student
student-> ":historyView":"requireSeeHistory()"
activate ":historyView"
":historyView"->":taskController":getHistory(id_user)
activate ":taskController"
activate ":task"
":taskController" -> ":task" :// getListTask()

":historyView"->":historyView":// displaydData()
activate ":historyView"
deactivate ":historyView"

@enduml